logo: # add logo name
title: Garden of Eden
description: > # this means to ignore newlines until "baseurl:"
  Garden-LLC, garden of eden, Boston, house, description.
permalink: :title/
#permalink: /:categories/:year/:month/:day/:title/
baseurl: "" #the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-img: gof-banner.png
banner-title: 伊甸园 # add banner title
banner-title-part2: 建筑装修有限责任公司 # add banner title
banner-desc: 您房屋的守护使者 # add banner description
banner-desc-part2:  # add banner description
company-eng-desc: "Dear friends,

Greetings. Garden of Eden LLC. was established in 2019 and has undergone four years of development. During this time, we have built a good reputation in the Boston area and established relatively
stable business relationships with many clients. Our company's employees consist of individuals from different age groups, including the elderly, middle-aged, and young. We work together to
complement each other's strengths and weaknesses and strive to meet our clients' needs with sincerity and cooperation.

Although there is still room for improvement, we will make our greatest effort to communicate with our clients and friends with sincerity. Our company's business operations cover all aspects of
family life in Boston and are an indispensable helper for your household. Please find below our past work experience, which we would like to showcase to everyone and hope to receive your valuable feedback.

Thank you!"
company-chi-desc: "亲爱的朋友们你们好：伊甸园建筑装修有限责任公司成立于2019年，经历了四年的发展，我们在大波士顿地区建立了良好的口碑，和很多客户拥有相对固定的业务往来。我们公司的员工由老，中，青三个年龄结构构成。互相取长补短，精诚合作，尽量满足客户的需求。虽然还有很多不足之处，我们会付出最大的努力和客户朋友们真诚的交流。我们公司经营业务覆盖了在波士顿家庭生活中的方方面面，是您家庭必不可少的帮手。下面是我们以往的工作经历，展示给大家，希望大家多提宝贵意见。 谢谢！"

# Author settings
author-pic: wechat-QR.jpg # your photo
author-name: Adam Xu # your name
about-author: Customer Manager of Garden of Eden-LLC.
author-desc : "Contact me with the Wechat QR code on the left or text me on whatsApp with the following phone number" # about author
email: x13604806293@gmail.com # your email
phone: (617)-765-9000 # your pnone number
website: https://garden-llc.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 9
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
